server:
  port: 8080

spring:
# 环境
  profiles:
    active: dev

#################### Druid连接池配置 start ########################
  datasource:
  druid:
    initial-size: 1
    max-active: 40
    min-idle: 20
    max-wait: 60000
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    validation-query: SELECT 'x'
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    filters: stat,slf4j
    # sql监控配置 filter
    web-stat-filter:
      url-pattern: /*
      exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      session-stat-enable: true
    # sql监控配置 servlet
    stat-view-servlet:
      url-pattern: /druid/*
      reset-enable: false
      login-username: admin
      login-password: admin
#################### Druid连接池配置 end ########################

# JPA配置 显示并格式化sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true

