spring:
#数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&amp;characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull&amp;failOverReadOnly=false&amp;autoReconnect=true&amp;roundRobinLoadBalance=true
    username: root
    password: root
